### ISSUE TITLE
Can't parse: BASE 101597441 +

### ISSUE THREAD

**Issue by gbetous** [ook/teleinfo#1]
Salut,

J'ai systématiquement l'erreur "Can't parse" sur la ligne BASE.
Pour info, j'ai l'abonnement minimal, sans même les HP/HC.

/home/pi/teleinfo/lib/teleinfo.rb:31:in `next': ["Can't parse: BASE 101597509 0"] (RuntimeError)
	from /home/pi/teleinfo/lib/teleinfo.rb:60:in `each'
	from /home/pi/.rvm/gems/ruby-2.1.3/gems/teleinfo-0.0.2/bin/teleinfo:20:in `<top (required)>'
	from /home/pi/.rvm/gems/ruby-2.1.3/bin/teleinfo:23:in `load'
	from /home/pi/.rvm/gems/ruby-2.1.3/bin/teleinfo:23:in `<main>'
	from /home/pi/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
	from /home/pi/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'

Merci !

**Comment by ook** [comment]
Merci. Peux-tu me fournir une ou deux minutes de trames s'il te plaît? Cache l'étiquette ADCO qui identifie ton compteur.

J'ajoute cette étiquette tout de suite.

**Comment by gbetous** [comment]
Voici une trame complète :+1: 
OPTARIF BASE 0
ISOUSC 30 9
BASE 101597537 1
PTEC TH.. $
IINST 003 Z
IMAX 027 H
PAPP 00780 0

**Comment by ook** [comment]
Hum, j'ai zappé OPTARIF, je rajoute.

**Comment by ook** [comment]
Ah non :p

**Comment by gbetous** [comment]
Pourtant ça a l'air bon :1234: 
{"adco":"xxxxxxxxxxx","optarif":"BASE","isousc":30,"base":101597623,"ptec":"TH","iinst":3,"imax":27,"papp":800}

**Comment by ook** [comment]
:+1:

**Comment by ook** [comment]
gem 0.0.3 gérant le tarif BASE disponible: https://rubygems.org/gems/teleinfo
