### ISSUE TITLE
Trace from EJP subscription

### ISSUE THREAD

**Issue by gbetous** [ook/teleinfo#2]
A friend took his trace. Don't know if you support his subscription, but maybe it can help.

Thanks !

ADCO yyyyyyyyyyyy D
OPTARIF BBR( S
ISOUSC 90 ?
BBRHCJB 044659149 G
BBRHPJB 106861212 E
BBRHCJW 009486954 _
BBRHPJW 017712424 [
BBRHCJR 005468651 P
BBRHPJR 009396630 ^
PTEC HPJB P
DEMAIN ---- "
IINST 022 [
IMAX 041 D
PAPP 05240 ,
HHPHC Y D
MOTDETAT 000000 B

**Comment by ook** [comment]
Thanks a lot, I'll implement it very soon!

**Comment by ook** [comment]
Handled by cf699aba20a0993f9387bbe3a1c5b5def4f57bbd

Thanks a lot!

**Comment by ook** [comment]
(Gem v0.0.4 released) https://rubygems.org/gems/teleinfo
